# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import larb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cicu', '0005_auto_20150420_0329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 8, 3, 1, 26, 50, 963925, tzinfo=utc))),
                ('text', models.TextField()),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cicu.UploadedFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'user_post',
            },
            bases=(models.Model, larb.models.PictureMixin),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(2017, 8, 3, 1, 26, 50, 966425, tzinfo=utc))),
                ('user_type', models.CharField(choices=[('MP', 'Medical Patient'), ('CN', 'Connoisseur'), ('BS', 'Business'), ('DR', 'Doctor'), ('DS', 'Dispensary')], default='MP', max_length=2)),
                ('rel_status', models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('DA', 'In Relationship'), ('JL', 'Just Looking'), ('EN', 'Engaged'), ('SE', 'Separated'), ('WI', 'Widowed')], default='SI', max_length=2)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FM', 'Female')], default='FM', max_length=2)),
                ('address', models.CharField(default='', max_length=200)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('US', 'United States'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('BZ', 'Belize'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('KH', 'Cambodia'), ('CL', 'Colombia'), ('CR', 'Costa Rica'), ('HR', 'Croatia'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('DE', 'Germany'), ('IN', 'India'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('MX', 'Mexico'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('PK', 'Pakistan'), ('PE', 'Peru'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('RU', 'Russia'), ('ES', 'Spain'), ('CH', 'Switzerland'), ('UA', 'Ukraine'), ('UY', 'Uruguay'), ('VI', 'U.S. Virgin Islands')], default='CA', max_length=50, verbose_name='Country')),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('CO', 'Colorado'), ('CA', 'California'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('IL', 'Illinois'), ('IA', 'Iowa'), ('KY', 'Kentucky')], default=None, max_length=50, null=True, verbose_name='State')),
                ('post_code', models.CharField(default='', max_length=12, verbose_name='Postal Code')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('company', models.CharField(blank=True, max_length=50)),
                ('has_accepted_tos', models.BooleanField(default=False, verbose_name='Accept site terms')),
                ('is_18_or_older', models.BooleanField(default=False, verbose_name='I am at least 18 years old')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privacy')),
                ('interested_in', models.CharField(choices=[('MA', 'Male'), ('FM', 'Female'), ('BI', 'Bi-Sexual')], default='BI', max_length=2)),
                ('maxdistance', models.SmallIntegerField(blank=True, default=250, validators=[django.core.validators.MaxValueValidator(2500), django.core.validators.MinValueValidator(1)])),
                ('cover_image', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_image', to='cicu.UploadedFile')),
                ('profile_image', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_image', to='cicu.UploadedFile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'user_profile',
            },
            bases=(models.Model, larb.models.PictureMixin),
        ),
    ]
