# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0002_auto_20170803_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 3, 29, 19, 351367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 4, 3, 29, 19, 354419, tzinfo=utc)),
        ),
    ]
