# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0004_auto_20170804_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 5, 43, 56, 544817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 9, 5, 43, 56, 546828, tzinfo=utc)),
        ),
    ]
