# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0005_auto_20170808_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 28, 18, 12, 46, 230553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 28, 18, 12, 46, 232552, tzinfo=utc)),
        ),
    ]
