# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0008_auto_20171122_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 17, 50, 10, 945737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 22, 17, 50, 10, 947735, tzinfo=utc)),
        ),
    ]
