# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0010_auto_20171122_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 7, 9, 30, 665718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='cicu.UploadedFile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 30, 7, 9, 30, 667718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='cicu.UploadedFile'),
        ),
    ]
