# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0011_auto_20171130_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 0, 14, 30, 487293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 4, 0, 14, 30, 489293, tzinfo=utc)),
        ),
    ]
