# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_auto_20150411_1556'),
        ('larb', '0012_auto_20171203_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='hashtags.HashTag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 22, 41, 18, 709462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 1, 17, 22, 41, 18, 711463, tzinfo=utc)),
        ),
    ]
