# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0014_auto_20180304_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 5, 6, 47, 600383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 15, 5, 6, 47, 602883, tzinfo=utc)),
        ),
    ]
