# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 05:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0015_auto_20180314_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 5, 3, 42, 822896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 26, 5, 3, 42, 826396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='cicu.ProfilePicture'),
        ),
    ]
