# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0016_auto_20180325_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 5, 42, 6, 730311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 26, 5, 42, 6, 732812, tzinfo=utc)),
        ),
    ]
