# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 19:20
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0018_auto_20180327_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 19, 20, 15, 983613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 27, 19, 20, 15, 986114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interested_in',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MA', 'Male'), ('FM', 'Female'), ('BI', 'Bi-Sexual')], default='BI', max_length=8), default=['BI'], size=3),
        ),
    ]
