# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0019_auto_20180327_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 18, 26, 30, 873313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 28, 18, 26, 30, 875814, tzinfo=utc)),
        ),
    ]
