# Generated by Django 2.0.7 on 2018-07-09 23:10

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('larb', '0020_auto_20180428_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 23, 10, 26, 874058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_image', to='cicu.UploadedFile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 9, 23, 10, 26, 876035, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interested_in',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MA', 'Male'), ('FM', 'Female'), ('TR', 'Transexual')], default='BI', max_length=8), default=['TR'], size=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_image', to='cicu.ProfilePicture'),
        ),
    ]
