from django.utils.translation import ugettext_lazy as _
#from .countries import COUNTRIES

ALABAMA = 'AL'
ALASKA = 'AK'
ARIZONA = 'AZ'
#ARKANSAS = 'AS'
CALIFORNIA = 'CA'
COLORADO = 'CO'
CONNECTICUT = 'CT'
DELAWARE = 'DE'
FLORIDA = 'FL'
GEORGIA = 'GA'
HAWAII = 'HI'
#IDAHO = 'ID'
ILLINOIS = 'IL'
#INDIANA = 'IN'
IOWA = 'IA'
#KANSAS = 'KS'
KENTUCKY = 'KY'
#LOUSIANA = 'LS'
MAINE = 'ME'
MARYLAND = 'MD'
MASSACHUSSETTS = 'MA'
MICHIGAN = 'MI'
MINNESOTA = 'MN'
MISSISSIPPI = 'MS'
MISSOURI = 'M0'
MONTANA = 'MT'
NEBRASKA = 'NE'
NEVADA = 'NV'
NEWHAMPSHIRE = 'NH'
NEWJERSEY = 'NJ'
NEWMEXICO = 'NM'
NEWYORK = 'NY'
NORTHCAROLINA = 'NC'
OHIO = 'OH'
OREGON = 'OR'
RHODEISLAND = 'RI'
SOUTHCAROLINA = 'SC'
TENNESSEE = 'TN'
TEXAS ='TX'
VERMONT = 'VT'
VIRGINIA = 'VA'
WASHINGTON = 'WA'
WISCONSIN = 'WI'
STATE_CODES = (
	ALABAMA,
	ALASKA,
	ARIZONA,
	CALIFORNIA,
	COLORADO,
	CONNECTICUT,
	DELAWARE,
	FLORIDA,
	GEORGIA,
	HAWAII,
	ILLINOIS,
	IOWA,
	KENTUCKY,
	MAINE,
	MARYLAND,
	MASSACHUSSETTS,
	MICHIGAN,
	MINNESOTA,
	MISSISSIPPI,
	MISSOURI,
	MONTANA,
	NEBRASKA,
	NEVADA,
	NEWHAMPSHIRE,
	NEWJERSEY,
	NEWMEXICO,
	NEWYORK,
	NORTHCAROLINA,
	OHIO,
	OREGON,
	RHODEISLAND,
	SOUTHCAROLINA,
	TENNESSEE,
	TEXAS,
	VERMONT,
	VIRGINIA,
	WASHINGTON,
	WISCONSIN,
)
STATES = (
	(ALABAMA, _(u'Alabama')),
	(ALASKA, _(u'Alaska')),
	(ARIZONA, _(u'Arizona')),
	(COLORADO, _(u'Colorado')),
	(CALIFORNIA, _(u'California')),
	(CONNECTICUT, _(u'Connecticut')),
	(DELAWARE, _(u'Delaware')),
	(FLORIDA, _(u'Florida')),
	(GEORGIA, _(u'Georgia')),
	(HAWAII, _(u'Hawaii')),
	(ILLINOIS, _(u'Illinois')),
	(IOWA, _(u'Iowa')),
	(KENTUCKY, _(u'Kentucky')),
)