# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 20:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20180428_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 20, 3, 22, 662965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 20, 3, 22, 662965, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='chatuser',
            unique_together=set([('room', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupchatuser',
            unique_together=set([('room', 'user')]),
        ),
    ]
