# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180428_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 20, 48, 46, 609167, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 20, 48, 46, 609167, tzinfo=utc)),
        ),
    ]
