# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-03 20:53
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180501_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouproom',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='grouproom',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 20, 53, 21, 589038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 20, 53, 21, 589038, tzinfo=utc)),
        ),
    ]
