# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 01:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180503_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouproom',
            name='expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 1, 22, 27, 254120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 1, 22, 27, 254120, tzinfo=utc)),
        ),
    ]
