# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20180626_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 44, 55, 431165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 26, 7, 44, 55, 431165, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 44, 55, 431165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 26, 7, 44, 55, 431165, tzinfo=utc), null=True),
        ),
    ]
