# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20180626_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatuser',
            old_name='active',
            new_name='activated',
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 8, 50, 48, 138271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 26, 8, 50, 48, 139271, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 8, 50, 48, 138271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 26, 8, 50, 48, 139271, tzinfo=utc), null=True),
        ),
    ]
