# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 19:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20180627_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 19, 43, 35, 901240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 29, 19, 43, 35, 901240, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 19, 43, 35, 901240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 29, 19, 43, 35, 901240, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
