# Generated by Django 2.0.7 on 2018-07-11 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20180709_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouproom',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 18, 6, 50, 82137, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='room',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 18, 6, 50, 82137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 18, 6, 50, 90137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 11, 18, 6, 50, 90137, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 18, 6, 50, 90137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groupchatuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 11, 18, 6, 50, 90137, tzinfo=utc), null=True),
        ),
    ]
