# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicu', '0008_auto_20180325_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'ordering': ('priority',), 'verbose_name': 'Profile Picture', 'verbose_name_plural': 'Profile Pictures'},
        ),
    ]
