# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 22:53
from __future__ import unicode_literals

import cicu.models
import cicu.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicu', '0009_auto_20180428_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=cicu.utils.upload_to, validators=[cicu.models.validate_file_type], verbose_name='file'),
        ),
    ]
