# Mirrors items reused server-side from constants.js

CHAT_LOGIN_SUCCESS = 'CHAT_LOGIN_SUCCESS'
RECEIVE_ROOMS = 'RECEIVE_ROOMS'
RECEIVE_MESSAGES = 'RECEIVE_MESSAGES'
CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM'

CREATE_CHAT_ROOM_SUCCESS = 'CREATE_CHAT_ROOM_SUCCESS'
CREATE_CHAT_ROOM_FAILURE = 'CREATE_CHAT_ROOM_FAILURE'
CLOSE_CHAT_ROOM = 'CLOSE_CHAT_ROOM'

DELETE_CHAT_ROOM = 'DELETE_CHAT_ROOM'
DELETE_CHAT_ROOM_SUCCESS = 'DELETE_CHAT_ROOM_SUCCESS'
DELETE_CHAT_ROOM_FAILURE = 'DELETE_CHAT_ROOM_FAILURE'

BLOCK_USER = 'BLOCK_USER'
BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
BLOCK_USER_FAILURE = 'BLOCK_USER_FAILURE'

UNBLOCK_USER = 'UNBLOCK_USER'
UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS'
UNBLOCK_USER_FAILURE = 'UNBLOCK_USER_FAILURE'

SET_ROOM_CONTENT = 'SET_ROOM_CONTENT'
SET_ROOM_INACTIVE = 'SET_ROOM_INACTIVE'
SET_ROOM_ACTIVE = 'SET_ROOM_ACTIVE'
SET_ROOM_IS_TYPING = 'SET_ROOM_IS_TYPING'

SET_ALL_ROOMS_INACTIVE_SUCCESS= 'SET_ALL_ROOMS_INACTIVE_SUCCESS'
SET_ALL_ROOMS_INACTIVE_FAILURE= 'SET_ALL_ROOMS_INACTIVE_FAILURE'

CREATE_MEET_MAP_ROOM_SUCCESS = 'CREATE_MEET_MAP_ROOM_SUCCESS'
CREATE_MEET_MAP_ROOM_FAILURE = 'CREATE_MEET_MAP_ROOM_FAILURE'

ACCEPT_JOIN_REQUEST_SUCCESS = 'ACCEPT_JOIN_REQUEST_SUCCESS'
ACCEPT_JOIN_REQUEST_FAILURE = 'ACCEPT_JOIN_REQUEST_FAILURE'

REJECT_JOIN_REQUEST_SUCCESS = 'REJECT_JOIN_REQUEST_SUCCESS'
REJECT_JOIN_REQUEST_FAILURE = 'REJECT_JOIN_REQUEST_FAILURE'

REQUEST_TO_JOIN_SUCCESS = 'REQUEST_TO_JOIN_SUCCESS'
REQUEST_TO_JOIN_FAILURE = 'REQUEST_TO_JOIN_FAILURE'