# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicu', '0005_auto_20150420_0329'),
        ('picture_comments', '0002_auto_20170928_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturecomment',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cicu.UploadedFile'),
        ),
    ]
