# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture_comments', '0003_picturecomment_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picturecomment',
            options={'ordering': ['-submit_date']},
        ),
        migrations.AlterField(
            model_name='picturecomment',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicu.UploadedFile'),
        ),
    ]
